### PR TITLE
Added modifiers to listen to scroll events

### PR DESCRIPTION
**Pull request by coreycoburn**
Added the ability to listen to scroll events. I added the scrollmonitor dependency to listen to the changes. I added 4 modifiers (enter, enterFully, exit, and exitPartially).

### CODE REVIEW

**Comment by coreycoburn** [comment]
``

**Comment by jofftiquez** [comment]
@coreycoburn wow thank you very much for this. Would you mind if I ask you to add this to the docs as well?

**Comment by coreycoburn** [comment]
Sure, I'll do that!

**Comment by jofftiquez** [comment]
@coreycoburn Thank you! You can edit the index.html in the root dir. It's a bit messy tho, I'll update to a better one as soon as you're done. Thank you so much. I'll merge this, then just do another PR for the docs. Cheers!

**Pull request merged**
